import Foundation

/// Zobrist hashing for chess positions.
///
/// Produces a stable 64-bit key for a board state so that identical positions —
/// reached by *any* move order — collapse to the same key. This is what makes
/// the GameStore position index transposition-aware.
///
/// The key tables are generated by a fixed-seed SplitMix64 PRNG, so the same
/// position hashes identically on every device and across app versions. NEVER
/// change the seed or the indexing scheme once a database has been built, or
/// previously-indexed positions will no longer match freshly-hashed ones.
enum Zobrist {

    // MARK: - Key tables (deterministic, lazily generated once)

    private struct Tables {
        let piece: [UInt64]      // 12 piece kinds x 64 squares = 768
        let side: UInt64         // XOR when Black is to move
        let castle: [UInt64]     // [WK, WQ, BK, BQ]
        let epFile: [UInt64]     // 8, by file of the en-passant target
    }

    private static let tables: Tables = {
        // SplitMix64 — fast, well-distributed, fully deterministic from a fixed seed.
        var state: UInt64 = 0x9E37_79B9_7F4A_7C15
        func nextKey() -> UInt64 {
            state = state &+ 0x9E37_79B9_7F4A_7C15
            var z = state
            z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
            z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
            return z ^ (z >> 31)
        }
        return Tables(
            piece:  (0..<768).map { _ in nextKey() },
            side:   nextKey(),
            castle: (0..<4).map { _ in nextKey() },
            epFile: (0..<8).map { _ in nextKey() }
        )
    }()

    /// Key of the standard starting position (handy for "find games from move 1").
    static let startPosition: UInt64 = Zobrist.hash(ChessBoard())

    // MARK: - Indexing

    /// 0...11 — type-major, white/black interleaved. Order is arbitrary but fixed.
    @inline(__always)
    private static func pieceIndex(_ piece: Piece) -> Int {
        pieceIndex(type: piece.type, color: piece.color)
    }

    @inline(__always)
    static func pieceIndex(type: PieceType, color: PieceColor) -> Int {
        let t: Int
        switch type {
        case .pawn:   t = 0
        case .knight: t = 1
        case .bishop: t = 2
        case .rook:   t = 3
        case .queen:  t = 4
        case .king:   t = 5
        }
        return t * 2 + (color == .white ? 0 : 1)
    }

    // Table accessors exposed for the flat ingest board (must produce identical keys).
    @inline(__always) static func pieceKey(pieceIndex: Int, square: Int) -> UInt64 { tables.piece[pieceIndex * 64 + square] }
    @inline(__always) static var sideToMoveKey: UInt64 { tables.side }
    @inline(__always) static func castlingKey(_ index: Int) -> UInt64 { tables.castle[index] }   // 0=WK,1=WQ,2=BK,3=BQ
    @inline(__always) static func enPassantFileKey(_ file: Int) -> UInt64 { tables.epFile[file] }

    // MARK: - Hashing

    /// Full hash of a board state, computed from scratch (O(64)). Cheap enough to
    /// call per ply during ingest; an incremental XOR variant is a later optimization.
    static func hash(_ board: ChessBoard) -> UInt64 {
        let t = tables
        var h: UInt64 = 0

        let squares = board.squares          // hoist the @Published nested array once
        for file in 0..<8 {
            let col = squares[file]
            for rank in 0..<8 {
                guard let piece = col[rank] else { continue }
                let square = rank * 8 + file        // 0...63
                h ^= t.piece[pieceIndex(piece) * 64 + square]
            }
        }

        if board.turn == .black { h ^= t.side }

        if board.whiteCanCastleKingside  { h ^= t.castle[0] }
        if board.whiteCanCastleQueenside { h ^= t.castle[1] }
        if board.blackCanCastleKingside  { h ^= t.castle[2] }
        if board.blackCanCastleQueenside { h ^= t.castle[3] }

        // En passant only counts when a pawn of the side-to-move can actually
        // capture (the Polyglot rule). Otherwise two positions that differ only by
        // an unusable EP target would hash differently and break transposition matching.
        if let ep = board.enPassantTarget, epIsCapturable(board, ep) {
            h ^= t.epFile[ep.file]
        }

        return h
    }

    /// SQLite stores signed 64-bit integers; store/query the bit pattern.
    @inline(__always)
    static func sqliteKey(_ board: ChessBoard) -> Int64 { Int64(bitPattern: hash(board)) }

    @inline(__always)
    static func sqliteKey(_ key: UInt64) -> Int64 { Int64(bitPattern: key) }

    private static func epIsCapturable(_ board: ChessBoard, _ ep: Position) -> Bool {
        // Side to move's capturing pawn sits on rank 4 (White) / rank 3 (Black), 0-indexed.
        let pawnRank = board.turn == .white ? 4 : 3
        let color = board.turn
        for df in [-1, 1] {
            let f = ep.file + df
            guard f >= 0 && f < 8 else { continue }
            if let p = board.squares[f][pawnRank], p.type == .pawn, p.color == color {
                return true
            }
        }
        return false
    }
}
