import Foundation

/// Encyclopedia of Chess Openings (ECO) code to opening name mapping
struct ECODatabase {
    static let openings: [String: String] = [
        // A00-A09: Uncommon Openings
        "A00": "Uncommon Opening",
        "A01": "Nimzowitsch-Larsen Attack",
        "A02": "Bird's Opening",
        "A03": "Bird's Opening",
        "A04": "Reti Opening",
        "A05": "Reti Opening",
        "A06": "Reti Opening",
        "A07": "King's Indian Attack",
        "A08": "King's Indian Attack",
        "A09": "Reti Opening",

        // A10-A39: English Opening
        "A10": "English Opening",
        "A11": "English Opening: Caro-Kann Defensive System",
        "A12": "English Opening: Caro-Kann Defensive System",
        "A13": "English Opening",
        "A14": "English Opening: Agincourt Defense",
        "A15": "English Opening: Anglo-Indian Defense",
        "A16": "English Opening: Anglo-Indian Defense",
        "A17": "English Opening: Hedgehog Defense",
        "A18": "English Opening: Mikenas-Carls Variation",
        "A19": "English Opening: Mikenas-Carls Variation",
        "A20": "English Opening",
        "A21": "English Opening",
        "A22": "English Opening: Two Knights Variation",
        "A23": "English Opening: Bremen System",
        "A24": "English Opening: Bremen System",
        "A25": "English Opening: Sicilian Reversed",
        "A26": "English Opening: Botvinnik System",
        "A27": "English Opening: Three Knights System",
        "A28": "English Opening: Four Knights System",
        "A29": "English Opening: Four Knights System",
        "A30": "English Opening: Symmetrical Variation",
        "A31": "English Opening: Symmetrical, Benoni Formation",
        "A32": "English Opening: Symmetrical Variation",
        "A33": "English Opening: Symmetrical Variation",
        "A34": "English Opening: Symmetrical Variation",
        "A35": "English Opening: Symmetrical Variation",
        "A36": "English Opening: Symmetrical Variation",
        "A37": "English Opening: Symmetrical Variation",
        "A38": "English Opening: Symmetrical Variation",
        "A39": "English Opening: Symmetrical, Main Line",

        // A40-A44: Queen's Pawn Game
        "A40": "Queen's Pawn Game",
        "A41": "Queen's Pawn Game: Robatsch Defense",
        "A42": "Modern Defense: Averbakh System",
        "A43": "Old Benoni Defense",
        "A44": "Old Benoni Defense",

        // A45-A49: Queen's Pawn Game
        "A45": "Queen's Pawn Game: Trompowsky Attack",
        "A46": "Queen's Pawn Game",
        "A47": "Queen's Indian Defense",
        "A48": "London System",
        "A49": "London System",

        // A50-A79: Indian Defenses
        "A50": "Queen's Pawn Game: Black Knights' Tango",
        "A51": "Budapest Gambit",
        "A52": "Budapest Gambit",
        "A53": "Old Indian Defense",
        "A54": "Old Indian Defense",
        "A55": "Old Indian Defense: Main Line",
        "A56": "Benoni Defense",
        "A57": "Benko Gambit",
        "A58": "Benko Gambit: Accepted",
        "A59": "Benko Gambit: Accepted, Main Line",
        "A60": "Benoni Defense",
        "A61": "Benoni Defense",
        "A62": "Benoni Defense: Fianchetto Variation",
        "A63": "Benoni Defense: Fianchetto Variation",
        "A64": "Benoni Defense: Fianchetto Variation",
        "A65": "Benoni Defense: Taimanov Variation",
        "A66": "Benoni Defense: Pawn Storm Variation",
        "A67": "Benoni Defense: Taimanov Variation",
        "A68": "Benoni Defense: Four Pawns Attack",
        "A69": "Benoni Defense: Four Pawns Attack, Main Line",
        "A70": "Benoni Defense: Classical Variation",
        "A71": "Benoni Defense: Classical Variation",
        "A72": "Benoni Defense: Classical Variation",
        "A73": "Benoni Defense: Classical Variation",
        "A74": "Benoni Defense: Classical Variation",
        "A75": "Benoni Defense: Classical Variation",
        "A76": "Benoni Defense: Classical Variation",
        "A77": "Benoni Defense: Classical Variation",
        "A78": "Benoni Defense: Classical Variation",
        "A79": "Benoni Defense: Classical Variation",

        // A80-A99: Dutch Defense
        "A80": "Dutch Defense",
        "A81": "Dutch Defense",
        "A82": "Dutch Defense: Staunton Gambit",
        "A83": "Dutch Defense: Staunton Gambit",
        "A84": "Dutch Defense",
        "A85": "Dutch Defense",
        "A86": "Dutch Defense: Leningrad Variation",
        "A87": "Dutch Defense: Leningrad Variation",
        "A88": "Dutch Defense: Leningrad Variation",
        "A89": "Dutch Defense: Leningrad Variation",
        "A90": "Dutch Defense",
        "A91": "Dutch Defense",
        "A92": "Dutch Defense",
        "A93": "Dutch Defense: Stonewall Variation",
        "A94": "Dutch Defense: Stonewall Variation",
        "A95": "Dutch Defense: Stonewall Variation",
        "A96": "Dutch Defense: Classical Variation",
        "A97": "Dutch Defense: Ilyin-Zhenevsky Variation",
        "A98": "Dutch Defense: Ilyin-Zhenevsky Variation",
        "A99": "Dutch Defense: Ilyin-Zhenevsky Variation",

        // B00-B09: Uncommon King's Pawn Defenses
        "B00": "Uncommon King's Pawn Opening",
        "B01": "Scandinavian Defense",
        "B02": "Alekhine's Defense",
        "B03": "Alekhine's Defense",
        "B04": "Alekhine's Defense: Modern Variation",
        "B05": "Alekhine's Defense: Modern Variation",
        "B06": "Modern Defense",
        "B07": "Pirc Defense",
        "B08": "Pirc Defense: Classical Variation",
        "B09": "Pirc Defense: Austrian Attack",

        // B10-B19: Caro-Kann Defense
        "B10": "Caro-Kann Defense",
        "B11": "Caro-Kann Defense: Two Knights Attack",
        "B12": "Caro-Kann Defense",
        "B13": "Caro-Kann Defense: Exchange Variation",
        "B14": "Caro-Kann Defense: Panov-Botvinnik Attack",
        "B15": "Caro-Kann Defense",
        "B16": "Caro-Kann Defense: Bronstein-Larsen Variation",
        "B17": "Caro-Kann Defense: Steinitz Variation",
        "B18": "Caro-Kann Defense: Classical Variation",
        "B19": "Caro-Kann Defense: Classical Variation",

        // B20-B99: Sicilian Defense
        "B20": "Sicilian Defense",
        "B21": "Sicilian Defense: Smith-Morra Gambit",
        "B22": "Sicilian Defense: Alapin Variation",
        "B23": "Sicilian Defense: Closed Variation",
        "B24": "Sicilian Defense: Closed Variation",
        "B25": "Sicilian Defense: Closed Variation",
        "B26": "Sicilian Defense: Closed Variation",
        "B27": "Sicilian Defense",
        "B28": "Sicilian Defense: O'Kelly Variation",
        "B29": "Sicilian Defense: Nimzowitsch Variation",
        "B30": "Sicilian Defense",
        "B31": "Sicilian Defense: Nyezhmetdinov-Rossolimo Attack",
        "B32": "Sicilian Defense: Open Variation",
        "B33": "Sicilian Defense: Pelikan Variation",
        "B34": "Sicilian Defense: Accelerated Dragon",
        "B35": "Sicilian Defense: Accelerated Dragon",
        "B36": "Sicilian Defense: Accelerated Dragon",
        "B37": "Sicilian Defense: Accelerated Dragon",
        "B38": "Sicilian Defense: Accelerated Dragon",
        "B39": "Sicilian Defense: Accelerated Dragon",
        "B40": "Sicilian Defense",
        "B41": "Sicilian Defense: Kan Variation",
        "B42": "Sicilian Defense: Kan Variation",
        "B43": "Sicilian Defense: Kan Variation",
        "B44": "Sicilian Defense: Taimanov Variation",
        "B45": "Sicilian Defense: Taimanov Variation",
        "B46": "Sicilian Defense: Taimanov Variation",
        "B47": "Sicilian Defense: Taimanov Variation",
        "B48": "Sicilian Defense: Taimanov Variation",
        "B49": "Sicilian Defense: Taimanov Variation",
        "B50": "Sicilian Defense",
        "B51": "Sicilian Defense: Moscow Variation",
        "B52": "Sicilian Defense: Moscow Variation",
        "B53": "Sicilian Defense",
        "B54": "Sicilian Defense",
        "B55": "Sicilian Defense",
        "B56": "Sicilian Defense",
        "B57": "Sicilian Defense: Sozin Attack",
        "B58": "Sicilian Defense: Boleslavsky Variation",
        "B59": "Sicilian Defense: Boleslavsky Variation",
        "B60": "Sicilian Defense: Richter-Rauzer Variation",
        "B61": "Sicilian Defense: Richter-Rauzer Variation",
        "B62": "Sicilian Defense: Richter-Rauzer Variation",
        "B63": "Sicilian Defense: Richter-Rauzer Variation",
        "B64": "Sicilian Defense: Richter-Rauzer Variation",
        "B65": "Sicilian Defense: Richter-Rauzer Variation",
        "B66": "Sicilian Defense: Richter-Rauzer Variation",
        "B67": "Sicilian Defense: Richter-Rauzer Variation",
        "B68": "Sicilian Defense: Richter-Rauzer Variation",
        "B69": "Sicilian Defense: Richter-Rauzer Variation",
        "B70": "Sicilian Defense: Dragon Variation",
        "B71": "Sicilian Defense: Dragon Variation",
        "B72": "Sicilian Defense: Dragon Variation",
        "B73": "Sicilian Defense: Dragon Variation",
        "B74": "Sicilian Defense: Dragon Variation",
        "B75": "Sicilian Defense: Dragon Variation",
        "B76": "Sicilian Defense: Dragon Variation, Yugoslav Attack",
        "B77": "Sicilian Defense: Dragon Variation, Yugoslav Attack",
        "B78": "Sicilian Defense: Dragon Variation, Yugoslav Attack",
        "B79": "Sicilian Defense: Dragon Variation, Yugoslav Attack",
        "B80": "Sicilian Defense: Scheveningen Variation",
        "B81": "Sicilian Defense: Scheveningen Variation",
        "B82": "Sicilian Defense: Scheveningen Variation",
        "B83": "Sicilian Defense: Scheveningen Variation",
        "B84": "Sicilian Defense: Scheveningen Variation",
        "B85": "Sicilian Defense: Scheveningen Variation",
        "B86": "Sicilian Defense: Sozin Attack",
        "B87": "Sicilian Defense: Sozin Attack",
        "B88": "Sicilian Defense: Sozin Attack",
        "B89": "Sicilian Defense: Sozin Attack",
        "B90": "Sicilian Defense: Najdorf Variation",
        "B91": "Sicilian Defense: Najdorf Variation",
        "B92": "Sicilian Defense: Najdorf Variation",
        "B93": "Sicilian Defense: Najdorf Variation",
        "B94": "Sicilian Defense: Najdorf Variation",
        "B95": "Sicilian Defense: Najdorf Variation",
        "B96": "Sicilian Defense: Najdorf Variation",
        "B97": "Sicilian Defense: Najdorf, Poisoned Pawn Variation",
        "B98": "Sicilian Defense: Najdorf Variation",
        "B99": "Sicilian Defense: Najdorf Variation, Main Line",

        // C00-C19: French Defense
        "C00": "French Defense",
        "C01": "French Defense: Exchange Variation",
        "C02": "French Defense: Advance Variation",
        "C03": "French Defense: Tarrasch Variation",
        "C04": "French Defense: Tarrasch Variation",
        "C05": "French Defense: Tarrasch Variation",
        "C06": "French Defense: Tarrasch Variation",
        "C07": "French Defense: Tarrasch Variation",
        "C08": "French Defense: Tarrasch Variation",
        "C09": "French Defense: Tarrasch Variation",
        "C10": "French Defense: Rubinstein Variation",
        "C11": "French Defense: Classical Variation",
        "C12": "French Defense: MacCutcheon Variation",
        "C13": "French Defense: Classical Variation",
        "C14": "French Defense: Classical Variation",
        "C15": "French Defense: Winawer Variation",
        "C16": "French Defense: Winawer Variation",
        "C17": "French Defense: Winawer Variation",
        "C18": "French Defense: Winawer Variation",
        "C19": "French Defense: Winawer Variation",

        // C20-C29: King's Pawn Game
        "C20": "King's Pawn Game",
        "C21": "Center Game",
        "C22": "Center Game",
        "C23": "Bishop's Opening",
        "C24": "Bishop's Opening",
        "C25": "Vienna Game",
        "C26": "Vienna Game",
        "C27": "Vienna Game",
        "C28": "Vienna Game",
        "C29": "Vienna Game",

        // C30-C39: King's Gambit
        "C30": "King's Gambit",
        "C31": "King's Gambit Declined",
        "C32": "King's Gambit Declined",
        "C33": "King's Gambit Accepted",
        "C34": "King's Gambit Accepted",
        "C35": "King's Gambit Accepted: Cunningham Defense",
        "C36": "King's Gambit Accepted: Abbazia Defense",
        "C37": "King's Gambit Accepted",
        "C38": "King's Gambit Accepted",
        "C39": "King's Gambit Accepted",

        // C40-C44: King's Knight Opening
        "C40": "King's Knight Opening",
        "C41": "Philidor Defense",
        "C42": "Petrov's Defense",
        "C43": "Petrov's Defense: Steinitz Attack",
        "C44": "King's Pawn Game",

        // C45-C49: Scotch Game and Four Knights
        "C45": "Scotch Game",
        "C46": "Three Knights Opening",
        "C47": "Four Knights Game",
        "C48": "Four Knights Game",
        "C49": "Four Knights Game",

        // C50-C59: Italian Game
        "C50": "Italian Game",
        "C51": "Italian Game: Evans Gambit",
        "C52": "Italian Game: Evans Gambit",
        "C53": "Italian Game: Classical Variation",
        "C54": "Italian Game: Classical Variation",
        "C55": "Italian Game: Two Knights Defense",
        "C56": "Italian Game: Two Knights Defense",
        "C57": "Italian Game: Two Knights Defense",
        "C58": "Italian Game: Two Knights Defense",
        "C59": "Italian Game: Two Knights Defense",

        // C60-C99: Ruy Lopez
        "C60": "Ruy Lopez",
        "C61": "Ruy Lopez: Bird's Defense",
        "C62": "Ruy Lopez: Steinitz Defense",
        "C63": "Ruy Lopez: Schliemann Defense",
        "C64": "Ruy Lopez: Classical Variation",
        "C65": "Ruy Lopez: Berlin Defense",
        "C66": "Ruy Lopez: Berlin Defense",
        "C67": "Ruy Lopez: Berlin Defense",
        "C68": "Ruy Lopez: Exchange Variation",
        "C69": "Ruy Lopez: Exchange Variation",
        "C70": "Ruy Lopez",
        "C71": "Ruy Lopez: Modern Steinitz Defense",
        "C72": "Ruy Lopez: Modern Steinitz Defense",
        "C73": "Ruy Lopez: Modern Steinitz Defense",
        "C74": "Ruy Lopez: Modern Steinitz Defense",
        "C75": "Ruy Lopez: Modern Steinitz Defense",
        "C76": "Ruy Lopez: Modern Steinitz Defense",
        "C77": "Ruy Lopez: Morphy Defense",
        "C78": "Ruy Lopez: Morphy Defense",
        "C79": "Ruy Lopez: Morphy Defense",
        "C80": "Ruy Lopez: Open Variation",
        "C81": "Ruy Lopez: Open Variation",
        "C82": "Ruy Lopez: Open Variation",
        "C83": "Ruy Lopez: Open Variation",
        "C84": "Ruy Lopez: Closed Variation",
        "C85": "Ruy Lopez: Closed Variation",
        "C86": "Ruy Lopez: Worrall Attack",
        "C87": "Ruy Lopez: Closed Variation",
        "C88": "Ruy Lopez: Closed Variation",
        "C89": "Ruy Lopez: Marshall Attack",
        "C90": "Ruy Lopez: Closed Variation",
        "C91": "Ruy Lopez: Closed Variation",
        "C92": "Ruy Lopez: Closed Variation",
        "C93": "Ruy Lopez: Closed Variation",
        "C94": "Ruy Lopez: Closed Variation",
        "C95": "Ruy Lopez: Closed Variation",
        "C96": "Ruy Lopez: Closed Variation",
        "C97": "Ruy Lopez: Closed Variation, Chigorin Defense",
        "C98": "Ruy Lopez: Closed Variation, Chigorin Defense",
        "C99": "Ruy Lopez: Closed Variation, Chigorin Defense",

        // D00-D05: Queen's Pawn Game
        "D00": "Queen's Pawn Game",
        "D01": "Richter-Veresov Attack",
        "D02": "Queen's Pawn Game",
        "D03": "Torre Attack",
        "D04": "Queen's Pawn Game: Colle System",
        "D05": "Queen's Pawn Game: Colle System",

        // D06-D69: Queen's Gambit
        "D06": "Queen's Gambit",
        "D07": "Queen's Gambit: Chigorin Defense",
        "D08": "Queen's Gambit Declined: Albin Countergambit",
        "D09": "Queen's Gambit Declined: Albin Countergambit",
        "D10": "Queen's Gambit Declined: Slav Defense",
        "D11": "Queen's Gambit Declined: Slav Defense",
        "D12": "Queen's Gambit Declined: Slav Defense",
        "D13": "Queen's Gambit Declined: Slav Defense, Exchange Variation",
        "D14": "Queen's Gambit Declined: Slav Defense, Exchange Variation",
        "D15": "Queen's Gambit Declined: Slav Defense",
        "D16": "Queen's Gambit Declined: Slav Defense",
        "D17": "Queen's Gambit Declined: Slav Defense",
        "D18": "Queen's Gambit Declined: Slav Defense",
        "D19": "Queen's Gambit Declined: Slav Defense",
        "D20": "Queen's Gambit Accepted",
        "D21": "Queen's Gambit Accepted",
        "D22": "Queen's Gambit Accepted",
        "D23": "Queen's Gambit Accepted",
        "D24": "Queen's Gambit Accepted",
        "D25": "Queen's Gambit Accepted",
        "D26": "Queen's Gambit Accepted",
        "D27": "Queen's Gambit Accepted: Classical Variation",
        "D28": "Queen's Gambit Accepted: Classical Variation",
        "D29": "Queen's Gambit Accepted: Classical Variation",
        "D30": "Queen's Gambit Declined",
        "D31": "Queen's Gambit Declined",
        "D32": "Queen's Gambit Declined: Tarrasch Defense",
        "D33": "Queen's Gambit Declined: Tarrasch Defense",
        "D34": "Queen's Gambit Declined: Tarrasch Defense",
        "D35": "Queen's Gambit Declined: Exchange Variation",
        "D36": "Queen's Gambit Declined: Exchange Variation",
        "D37": "Queen's Gambit Declined",
        "D38": "Queen's Gambit Declined: Ragozin Defense",
        "D39": "Queen's Gambit Declined: Ragozin Defense",
        "D40": "Queen's Gambit Declined: Semi-Tarrasch Defense",
        "D41": "Queen's Gambit Declined: Semi-Tarrasch Defense",
        "D42": "Queen's Gambit Declined: Semi-Tarrasch Defense",
        "D43": "Queen's Gambit Declined: Semi-Slav Defense",
        "D44": "Queen's Gambit Declined: Semi-Slav Defense",
        "D45": "Queen's Gambit Declined: Semi-Slav Defense",
        "D46": "Queen's Gambit Declined: Semi-Slav Defense",
        "D47": "Queen's Gambit Declined: Semi-Slav Defense, Meran Variation",
        "D48": "Queen's Gambit Declined: Semi-Slav Defense, Meran Variation",
        "D49": "Queen's Gambit Declined: Semi-Slav Defense, Meran Variation",
        "D50": "Queen's Gambit Declined",
        "D51": "Queen's Gambit Declined",
        "D52": "Queen's Gambit Declined",
        "D53": "Queen's Gambit Declined",
        "D54": "Queen's Gambit Declined",
        "D55": "Queen's Gambit Declined",
        "D56": "Queen's Gambit Declined: Lasker Defense",
        "D57": "Queen's Gambit Declined: Lasker Defense",
        "D58": "Queen's Gambit Declined: Tartakower Variation",
        "D59": "Queen's Gambit Declined: Tartakower Variation",
        "D60": "Queen's Gambit Declined: Orthodox Defense",
        "D61": "Queen's Gambit Declined: Orthodox Defense",
        "D62": "Queen's Gambit Declined: Orthodox Defense",
        "D63": "Queen's Gambit Declined: Orthodox Defense",
        "D64": "Queen's Gambit Declined: Orthodox Defense",
        "D65": "Queen's Gambit Declined: Orthodox Defense",
        "D66": "Queen's Gambit Declined: Orthodox Defense",
        "D67": "Queen's Gambit Declined: Orthodox Defense",
        "D68": "Queen's Gambit Declined: Orthodox Defense",
        "D69": "Queen's Gambit Declined: Orthodox Defense",

        // D70-D99: Grunfeld Defense
        "D70": "Neo-Grunfeld Defense",
        "D71": "Neo-Grunfeld Defense",
        "D72": "Neo-Grunfeld Defense",
        "D73": "Neo-Grunfeld Defense",
        "D74": "Neo-Grunfeld Defense",
        "D75": "Neo-Grunfeld Defense",
        "D76": "Neo-Grunfeld Defense",
        "D77": "Neo-Grunfeld Defense",
        "D78": "Neo-Grunfeld Defense",
        "D79": "Neo-Grunfeld Defense",
        "D80": "Grunfeld Defense",
        "D81": "Grunfeld Defense",
        "D82": "Grunfeld Defense",
        "D83": "Grunfeld Defense",
        "D84": "Grunfeld Defense",
        "D85": "Grunfeld Defense",
        "D86": "Grunfeld Defense: Exchange Variation",
        "D87": "Grunfeld Defense: Exchange Variation",
        "D88": "Grunfeld Defense: Exchange Variation",
        "D89": "Grunfeld Defense: Exchange Variation",
        "D90": "Grunfeld Defense",
        "D91": "Grunfeld Defense",
        "D92": "Grunfeld Defense",
        "D93": "Grunfeld Defense",
        "D94": "Grunfeld Defense",
        "D95": "Grunfeld Defense",
        "D96": "Grunfeld Defense: Russian Variation",
        "D97": "Grunfeld Defense: Russian Variation",
        "D98": "Grunfeld Defense: Russian Variation",
        "D99": "Grunfeld Defense: Russian Variation",

        // E00-E09: Catalan Opening
        "E00": "Queen's Pawn Game",
        "E01": "Catalan Opening",
        "E02": "Catalan Opening",
        "E03": "Catalan Opening",
        "E04": "Catalan Opening: Open Defense",
        "E05": "Catalan Opening: Open Defense",
        "E06": "Catalan Opening: Closed Variation",
        "E07": "Catalan Opening: Closed Variation",
        "E08": "Catalan Opening: Closed Variation",
        "E09": "Catalan Opening: Closed Variation",

        // E10-E19: Queen's Pawn Game
        "E10": "Queen's Pawn Game",
        "E11": "Bogo-Indian Defense",
        "E12": "Queen's Indian Defense",
        "E13": "Queen's Indian Defense",
        "E14": "Queen's Indian Defense",
        "E15": "Queen's Indian Defense",
        "E16": "Queen's Indian Defense",
        "E17": "Queen's Indian Defense",
        "E18": "Queen's Indian Defense",
        "E19": "Queen's Indian Defense",

        // E20-E59: Nimzo-Indian Defense
        "E20": "Nimzo-Indian Defense",
        "E21": "Nimzo-Indian Defense",
        "E22": "Nimzo-Indian Defense",
        "E23": "Nimzo-Indian Defense",
        "E24": "Nimzo-Indian Defense: Samisch Variation",
        "E25": "Nimzo-Indian Defense: Samisch Variation",
        "E26": "Nimzo-Indian Defense: Samisch Variation",
        "E27": "Nimzo-Indian Defense: Samisch Variation",
        "E28": "Nimzo-Indian Defense: Samisch Variation",
        "E29": "Nimzo-Indian Defense: Samisch Variation",
        "E30": "Nimzo-Indian Defense: Leningrad Variation",
        "E31": "Nimzo-Indian Defense: Leningrad Variation",
        "E32": "Nimzo-Indian Defense: Classical Variation",
        "E33": "Nimzo-Indian Defense: Classical Variation",
        "E34": "Nimzo-Indian Defense: Classical Variation",
        "E35": "Nimzo-Indian Defense: Classical Variation",
        "E36": "Nimzo-Indian Defense: Classical Variation",
        "E37": "Nimzo-Indian Defense: Classical Variation",
        "E38": "Nimzo-Indian Defense: Classical Variation",
        "E39": "Nimzo-Indian Defense: Classical Variation",
        "E40": "Nimzo-Indian Defense",
        "E41": "Nimzo-Indian Defense: Hubner Variation",
        "E42": "Nimzo-Indian Defense: Hubner Variation",
        "E43": "Nimzo-Indian Defense",
        "E44": "Nimzo-Indian Defense",
        "E45": "Nimzo-Indian Defense",
        "E46": "Nimzo-Indian Defense: Reshevsky Variation",
        "E47": "Nimzo-Indian Defense",
        "E48": "Nimzo-Indian Defense",
        "E49": "Nimzo-Indian Defense",
        "E50": "Nimzo-Indian Defense",
        "E51": "Nimzo-Indian Defense",
        "E52": "Nimzo-Indian Defense",
        "E53": "Nimzo-Indian Defense",
        "E54": "Nimzo-Indian Defense",
        "E55": "Nimzo-Indian Defense",
        "E56": "Nimzo-Indian Defense",
        "E57": "Nimzo-Indian Defense",
        "E58": "Nimzo-Indian Defense",
        "E59": "Nimzo-Indian Defense",

        // E60-E99: King's Indian Defense
        "E60": "King's Indian Defense",
        "E61": "King's Indian Defense",
        "E62": "King's Indian Defense: Fianchetto Variation",
        "E63": "King's Indian Defense: Fianchetto Variation",
        "E64": "King's Indian Defense: Fianchetto Variation",
        "E65": "King's Indian Defense: Fianchetto Variation",
        "E66": "King's Indian Defense: Fianchetto Variation",
        "E67": "King's Indian Defense: Fianchetto Variation",
        "E68": "King's Indian Defense: Fianchetto Variation",
        "E69": "King's Indian Defense: Fianchetto Variation",
        "E70": "King's Indian Defense",
        "E71": "King's Indian Defense",
        "E72": "King's Indian Defense",
        "E73": "King's Indian Defense",
        "E74": "King's Indian Defense: Averbakh Variation",
        "E75": "King's Indian Defense: Averbakh Variation",
        "E76": "King's Indian Defense: Four Pawns Attack",
        "E77": "King's Indian Defense: Four Pawns Attack",
        "E78": "King's Indian Defense: Four Pawns Attack",
        "E79": "King's Indian Defense: Four Pawns Attack",
        "E80": "King's Indian Defense: Samisch Variation",
        "E81": "King's Indian Defense: Samisch Variation",
        "E82": "King's Indian Defense: Samisch Variation",
        "E83": "King's Indian Defense: Samisch Variation",
        "E84": "King's Indian Defense: Samisch Variation",
        "E85": "King's Indian Defense: Samisch Variation",
        "E86": "King's Indian Defense: Samisch Variation",
        "E87": "King's Indian Defense: Samisch Variation",
        "E88": "King's Indian Defense: Samisch Variation",
        "E89": "King's Indian Defense: Samisch Variation",
        "E90": "King's Indian Defense",
        "E91": "King's Indian Defense",
        "E92": "King's Indian Defense: Classical Variation",
        "E93": "King's Indian Defense: Classical Variation",
        "E94": "King's Indian Defense: Classical Variation",
        "E95": "King's Indian Defense: Classical Variation",
        "E96": "King's Indian Defense: Classical Variation",
        "E97": "King's Indian Defense: Mar del Plata Variation",
        "E98": "King's Indian Defense: Mar del Plata Variation",
        "E99": "King's Indian Defense: Mar del Plata Variation"
    ]

    /// Get opening name for an ECO code
    static func openingName(for eco: String) -> String? {
        return openings[eco.uppercased()]
    }

    /// Get opening name for an ECO code, with fallback to the code itself
    static func openingNameOrCode(for eco: String) -> String {
        return openings[eco.uppercased()] ?? eco
    }
}
